export interface Pirate {
    id: number;
    name: string;
  }
export const PIRATES: Pirate[] = [
    { id: 1, name: 'Roger Pirates' },
    { id: 2, name: 'Red Hair Pirates' },
    { id: 3, name: 'Rocks Pirates' },
    { id: 4, name: 'Whitebeard Pirates' },
    { id: 5, name: 'Big Mom Pirates' },
    { id: 6, name: 'Straw Hat Pirates' },
    { id: 7, name: 'Golden Lion Pirates' },
    { id: 8, name: 'Beast pirates' },
    { id: 9, name: 'Blackbeard Fleet' },
    { id: 10, name: 'Donquixote Pirates' },
    { id: 11, name: 'Straw Hat Grand Fleet' },
    { id: 12, name: 'Heart Pirates' },
    { id: 13, name: 'Sun Pirates' },
    { id: 14, name: 'Kuja Nation' },
    { id: 15, name: 'Spade Pirates' },
    { id: 16, name: 'On-Air Pirates' },
    { id: 17, name: 'Thriller Bark Pirates' },
    { id: 18, name: 'Fire Tank Pirates' },
    { id: 19, name: 'X-Drake Pirates' },
    { id: 20, name: 'Hawkins Pirates' },
    // { id: 21 , name: 'a'},
    // { id: 22 , name: 'a'},
    // { id: 23 , name: 'a'},
    // { id: 24 , name: 'a'},
    // { id: 25 , name: 'a'},
    // { id: 26 , name: 'a'},
    // { id: 27 , name: 'a'},
    // { id: 28 , name: 'a'},
    // { id: 29 , name: 'a'},
    // { id: 30 , name: 'a'},
    // { id: 31 , name: 'a'},
    // { id: 32 , name: 'a'},
    // { id: 33 , name: 'a'},
    // { id: 34 , name: 'a'},
    // { id: 35 , name: 'a'},
    // { id: 36 , name: 'a'},
    // { id: 37 , name: 'a'},
    // { id: 38 , name: 'a'},
    // { id: 39 , name: 'a'},
    // { id: 40 , name: 'a'},
    
  ];